Change TabBar to BottomNavigationBar
VictorUvarov/provider_architecture_template pull request #3
Opened 2019-10-22 15:34 UTC by ferrarafer

This option works using IndexedStack.

2019-10-22 17:30 UTC, VictorUvarov requested changes
This looks good, but I would like the change tab to be `model.changeTab(index)`. Which means `MainView` would need a model. Also, someone using the architecture might want a tab view or nav bar view. So maybe creating two files might be the best option.

2019-10-22 18:40 UTC, ferrarafer commented
> This looks good, but I would like the change tab to be `model.changeTab(index)`. Which means `MainView` would need a model. Also, someone using the architecture might want a tab view or nav bar view. So maybe creating two files might be the best option.

What do you mean with someone might want a TabBarView?

2019-10-22 21:57 UTC, VictorUvarov commented on lib/ui/views/main_view.dart
>  class _MainViewState extends State<MainView> {
The main view doesn't need to be stateful anymore.

2019-10-22 21:58 UTC, VictorUvarov commented on lib/core/ui_models/views/main_model.dart
> +  void changeTab(index) {
change to 
```dart 
int index
```

2019-10-22 21:59 UTC, VictorUvarov commented on lib/core/ui_models/views/main_model.dart
> +    setState(ViewState.Idle);
don't need to setState(...) twice, just  call once with
```dart
notifyListeners();
```

2019-10-22 22:00 UTC, VictorUvarov requested changes
few changes

2019-10-23 14:16 UTC, VictorUvarov approved these changes

2019-10-23 14:16 UTC, merged