Snackbar service addition
VictorUvarov/provider_architecture_template pull request #6
Opened 2020-03-03 04:37 UTC by odunboye

I added snackbar service using flushbar package.
A sample usage exist in login_view_model

2020-03-03 21:09 UTC, VictorUvarov commented on lib/core/managers/snack_bar_manager.dart
> +        onPressed: () {},
Add a @nullable `void Function() get onPressed` to ConfirmSnackBarRequest to be used here

2020-03-03 21:20 UTC, VictorUvarov commented on lib/core/managers/snack_bar_manager.dart
> +      backgroundColor: Colors.red,
Remove the hard-coded background color

2020-03-03 21:21 UTC, VictorUvarov commented on lib/core/models/post/post_h.g.dart
> -          typeId == other.typeId;
Without these lines the tests won't pass. Please manually re add them.

2020-03-03 21:22 UTC, VictorUvarov commented on lib/core/models/snack_bar_request/confirm_snack_bar_request.dart
> +  String get childtext;
Add a space inbetween these getters. Also add @nullable `void Function() get onPressed`

2020-03-03 21:23 UTC, VictorUvarov commented on lib/core/models/user/user_h.g.dart
> -          typeId == other.typeId;
Without these lines the tests won't pass. Please manually re add them.

2020-03-03 21:23 UTC, VictorUvarov commented on lib/core/view_models/login_view_model.dart
> +  final _snackBarService = locator<SnackBarService>();
Add a space after this line to separate the services from the controllers

2020-03-03 21:25 UTC, VictorUvarov commented on lib/core/view_models/login_view_model.dart
> +
Uncomment and move this to the settings service notifications toggle to have a demo in the app instead of just the comments.

2020-03-03 21:26 UTC, VictorUvarov commented on lib/core/view_models/login_view_model.dart
> +import '../../locator.dart';
Replace this with a package import instead.

2020-03-03 21:27 UTC, VictorUvarov requested changes
Looks pretty good. Some minor changes. Is it possible to do this without the Flushbar Plugin depedency?

2020-03-04 20:55 UTC, odunboye commented
> Looks pretty good. Some minor changes. Is it possible to do this without the Flushbar Plugin depedency?

I have not figured out how to wrap the flutter Snackbar in a service yet.

2020-03-05 00:47 UTC, VictorUvarov commented on lib/core/models/snack_bar_request/confirm_snack_bar_request.dart
> +  String get childtext;
spelling: childtext => childText

2020-03-05 00:48 UTC, VictorUvarov commented on lib/core/view_models/login_view_model.dart
> +
remove empty line

2020-03-05 00:48 UTC, VictorUvarov commented on lib/core/view_models/settings_view_model.dart
> +      ..duration = duration);
add trailing comma

2020-03-05 00:48 UTC, VictorUvarov commented on lib/core/view_models/settings_view_model.dart
> +      {String message, String childText, int colorCode, int duration}) async {
add trailing comma

2020-03-05 00:49 UTC, VictorUvarov commented on assets/lang/en.json
> +}
add new line at end of file

2020-03-05 00:49 UTC, VictorUvarov commented on assets/lang/es.json
> +}
add new line at end of file

2020-03-05 00:49 UTC, VictorUvarov commented on assets/lang/ru.json
> +}
add new line at end of file

2020-03-05 00:50 UTC, VictorUvarov requested changes
Looks good just some minor changes

2020-03-05 19:12 UTC, VictorUvarov approved these changes
Looks good. I've already added this into my other apps. Works very well.

2020-03-05 19:12 UTC, merged

2020-03-05 19:14 UTC, odunboye commented
Great, thanks!